communaute-de-commune-coeur-essonne:
  participer-a-des-echanges-pour-ameliorer-ses-chances-d-acces-a-l-emploi-cafe-accueil-emploi:
    -
      -
        attribute: "awareness"
        operator: "=="
        value: "Je ne sais pas ce que je veux faire"

      -
        attribute: "experience"
        operator: "=="
        value: false

      -
        attribute: "duration"
        operator: "in?"
        value:
          - "Quelques mois"
          - "1 an"
          - "+ d'1 an"

      -
        attribute: "status"
        operator: "in?"
        value:
          - "Sans activité"
          - "Étudiant·e"
          - "Lycéen·ne"
          - "Salarié·e"
          - "En formation"
          - "Apprenti·e"
          - "Autre"

      -
        attribute: "last_class"
        operator: "in?"
        value:
          - "Collège"
          - "Lycée"
          - "Aprentissage"
          - "Études supérieures"
          - "Autre"

      -
        attribute: "age"
        operator: "<="
        value: 30

      -
        attribute: "city"
        operator: "in?"
        value:
          - "Arpajon"
          - "Avrainville"
          - "Brétigny-sur-Orge"
          - "Breuillet"
          - "Bruyères-le-Châtel"
          - "Cheptainville"
          - "Egly"
          - "Fleury-Mérogis"
          - "Guibeville"
          - "La Norville"
          - "Le Plessis-Pâté"
          - "Leuville-sur-Orge"
          - "Longpont-sur-Orge"
          - "Marolles-en-Hurepoix"
          - "Morsang-sur-Orge"
          - "Ollainville"
          - "Saint-Germain-lès-Arpajon"
          - "Saint-Michel-sur-Orge"
          - "Sainte-Genviève-des-Bois"
          - "Villemoisson-sur-Orge"
          - "Villiers-sur-Orge"

  participer-a-des-job-dating-des-forums-pour-l-emploi-des-cellules-de-recrutement:
   -
    -
      attribute: "awareness"
      operator: "=="
      value: "Je ne sais pas ce que je veux faire"

    -
      attribute: "experience"
      operator: "=="
      value: false

    -
      attribute: "duration"
      operator: "in?"
      value:
        - "Quelques mois"
        - "1 an"
        - "+ d'1 an"

    -
      attribute: "status"
      operator: "in?"
      value:
        - "Sans activité"
        - "Étudiant·e"
        - "Lycéen·ne"
        - "Salarié·e"
        - "En formation"
        - "Apprenti·e"
        - "Autre"

    -
      attribute: "last_class"
      operator: "in?"
      value:
        - "Collège"
        - "Lycée"
        - "Aprentissage"
        - "Études supérieures"
        - "Autre"
    -
      attribute: "age"
      operator: "<="
      value: 30

    -
      attribute: "city"
      operator: "in?"
      value:
        - "Arpajon"
        - "Avrainville"
        - "Brétigny-sur-Orge"
        - "Breuillet"
        - "Bruyères-le-Châtel"
        - "Cheptainville"
        - "Egly"
        - "Fleury-Mérogis"
        - "Guibeville"
        - "La Norville"
        - "Le Plessis-Pâté"
        - "Leuville-sur-Orge"
        - "Longpont-sur-Orge"
        - "Marolles-en-Hurepoix"
        - "Morsang-sur-Orge"
        - "Ollainville"
        - "Saint-Germain-lès-Arpajon"
        - "Saint-Michel-sur-Orge"
        - "Sainte-Genviève-des-Bois"
        - "Villemoisson-sur-Orge"
        - "Villiers-sur-Orge"

  participer-a-des-rendez-vous-formation-avec-des-experts-de-l-information-sur-les-metiers-et-sur-les-formations-pour-y-acceder:
    -
      -
        attribute: "awareness"
        operator: "=="
        value: "Je ne sais pas ce que je veux faire"

      -
        attribute: "experience"
        operator: "=="
        value: false

      -
        attribute: "duration"
        operator: "in?"
        value:
          - "Quelques mois"
          - "1 an"
          - "+ d'1 an"

      -
        attribute: "status"
        operator: "in?"
        value:
          - "Sans activité"
          - "Étudiant·e"
          - "Lycéen·ne"
          - "Salarié·e"
          - "En formation"
          - "Apprenti·e"
          - "Autre"

      -
        attribute: "last_class"
        operator: "in?"
        value:
          - "Collège"
          - "Lycée"
          - "Aprentissage"
          - "Études supérieures"
          - "Autre"

      -
        attribute: "age"
        operator: "<="
        value: 30

      -
        attribute: "city"
        operator: "in?"
        value:
          - "Arpajon"
          - "Avrainville"
          - "Brétigny-sur-Orge"
          - "Breuillet"
          - "Bruyères-le-Châtel"
          - "Cheptainville"
          - "Egly"
          - "Fleury-Mérogis"
          - "Guibeville"
          - "La Norville"
          - "Le Plessis-Pâté"
          - "Leuville-sur-Orge"
          - "Longpont-sur-Orge"
          - "Marolles-en-Hurepoix"
          - "Morsang-sur-Orge"
          - "Ollainville"
          - "Saint-Germain-lès-Arpajon"
          - "Saint-Michel-sur-Orge"
          - "Sainte-Genviève-des-Bois"
          - "Villemoisson-sur-Orge"
          - "Villiers-sur-Orge"

  etre-recu-rapidement-par-un-correspondant-emploi-dans-une-permanence-pres-de-chez-moi:

    -
      -
        attribute: "awareness"
        operator: "=="
        value: "Je ne sais pas ce que je veux faire"

      -
        attribute: "experience"
        operator: "=="
        value: false

      -
        attribute: "duration"
        operator: "in?"
        value:
          - "Quelques mois"
          - "1 an"
          - "+ d'1 an"

      -
        attribute: "status"
        operator: "in?"
        value:
          - "Sans activité"
          - "Étudiant·e"
          - "Lycéen·ne"
          - "Salarié·e"
          - "En formation"
          - "Apprenti·e"
          - "Autre"

      -
        attribute: "last_class"
        operator: "in?"
        value:
          - "Collège"
          - "Lycée"
          - "Aprentissage"
          - "Études supérieures"
          - "Autre"

      -
        attribute: "age"
        operator: "<="
        value: 30

      -
        attribute: "city"
        operator: "in?"
        value:
          - "Arpajon"
          - "Avrainville"
          - "Brétigny-sur-Orge"
          - "Breuillet"
          - "Bruyères-le-Châtel"
          - "Cheptainville"
          - "Egly"
          - "Fleury-Mérogis"
          - "Guibeville"
          - "La Norville"
          - "Le Plessis-Pâté"
          - "Leuville-sur-Orge"
          - "Longpont-sur-Orge"
          - "Marolles-en-Hurepoix"
          - "Morsang-sur-Orge"
          - "Ollainville"
          - "Saint-Germain-lès-Arpajon"
          - "Saint-Michel-sur-Orge"
          - "Sainte-Genviève-des-Bois"
          - "Villemoisson-sur-Orge"
          - "Villiers-sur-Orge"

