crij-centre-regional-d-information-jeunesse: # code  acteur A
  decouvrir-les-solutions-logement-sur-ton-territoire: # code offre de service A
    # scenarios
    -
      # conditions for each scenario
      -
        attribute: "duration" # discriminant @see app/models/service_offering.rb
        operator: "in?" # options are ==, >=, >, <, <=, in?
        value:
          - "Quelques mois"
          - "1 an"
          - "+ d'1 an"
      -
        attribute: "resources" # discriminant @see app/models/service_offering.rb
        operator: ">=" # options are ==, >=, >, <, <=, in?
        value: 150
      -
        attribute: "current_status" # discriminant @see app/models/service_offering.rb
        operator: "in?" # options are ==, >=, >, <, <=, in?
        value:
          - "Étudiant·e"
          - "Lycéen·ne"
          - "Salarié·e"
          - "En formation"
          - "Apprenti·e"

bureau-d-accueil-au-logement-social-comal-soliha:
  faire-une-demande-d-aide-au-financement-de-ton-logement-avec-le-conseil-departemental: # Les aides au financement du logement seraient plus pertinentes pour un utilisateur qui rechercheun emploi, une formation... qu'un logement
    -
      -
        attribute: "duration"
        operator: "==" # when we use de in? operator, value must be formated as below
        value: "+ d'1 an"
      -
        attribute: "resources" # discriminant @see app/models/service_offering.rb
        operator: ">=" # options are ==, >=, >, <, <=, in?
        value: 500
      -
        attribute: "current_status" # discriminant @see app/models/service_offering.rb
        operator: "in?" # options are ==, >=, >, <, <=, in?
        value:
          - "Salarié·e"
          - "En formation"
          - "Apprenti·e"

  faire-une-demande-de-logement-social:
    -
      -
        attribute: "duration"
        operator: "==" # when we use de in? operator, value must be formated as below
        value: "+ d'1 an"
      -
        attribute: "resources" # discriminant @see app/models/service_offering.rb
        operator: ">=" # options are ==, >=, >, <, <=, in?
        value: 500
      -
        attribute: "current_status" # discriminant @see app/models/service_offering.rb
        operator: "in?" # options are ==, >=, >, <, <=, in?
        value:
          - "Salarié·e"
          - "En formation"
          - "Apprenti·e"

foyer-de-jeunes-travailleurs-fjt-leon-paindavoine:
  favoriser-la-rencontre-et-le-partage-avec-d-autres-jeunes:
    -
      -
        attribute: "duration"
        operator: "in?" # options are ==, >=, >, <, <=, in?
        value:
          - "Quelques mois"
          - "1 an"
          - "+ d'1 an"
      -
        attribute: "resources" # discriminant @see app/models/service_offering.rb
        operator: ">=" # options are ==, >=, >, <, <=, in?
        value: 300
      -
        attribute: "current_status" # discriminant @see app/models/service_offering.rb
        operator: "in?" # options are ==, >=, >, <, <=, in?
        value:
          - "Étudiant·e"
          - "Salarié·e"
          - "En formation"
          - "Apprenti·e"

caisse-d-allocations-familiales-caf:
  simuler-le-montant-de-ton-aide-au-logement-2271b89b-1231-4a94-8ec4-e94813ed4694:
    -
      -
        attribute: "duration"
        operator: "in?" # options are ==, >=, >, <, <=, in?
        value:
          - "Quelques mois"
          - "1 an"
          - "+ d'1 an"

espace-metiers:
  t-accompagner-pour-trouver-une-solution-d-hebergement-ou-de-logement:
    -
      -
        attribute: "duration"
        operator: "in?" # options are ==, >=, >, <, <=, in?
        value:
          - "Quelques mois"
          - "1 an"
          - "+ d'1 an"
      -
        attribute: "resources" # discriminant @see app/models/service_offering.rb
        operator: ">=" # options are ==, >=, >, <, <=, in?
        value: 300
      -
        attribute: "current_status" # discriminant @see app/models/service_offering.rb
        operator: "in?" # options are ==, >=, >, <, <=, in?
        value:
          - "Étudiant·e"
          - "Salarié·e"
          - "En formation"
          - "Apprenti·e"

crous-reims-centre-regional-des-oeuvres-universitaires-et-scolaires-acal:
  t-aider-a-obtenir-une-aide-financiere-ponctuelle-en-cas-de-difficulte-a-payer-ton-loyer: # Les aides au financement du logement seraient plus pertinentes pour un utilisateur qui rechercheun emploi, une formation... qu'un logement
    -
      -
        attribute: "duration"
        operator: "in?" # options are ==, >=, >, <, <=, in?
        value:
          - "Quelques mois"
          - "1 an"
          - "+ d'1 an"
      -
        attribute: "resources" # discriminant @see app/models/service_offering.rb
        operator: "<=" # options are ==, >=, >, <, <=, in?
        value: 1000
      -
        attribute: "current_status" # discriminant @see app/models/service_offering.rb
        operator: "==" # options are ==, >=, >, <, <=, in?
        value: "Étudiant·e"

  t-informer-sur-le-logement-en-residence-universitaire-9bcb5319-b3de-46c0-be0b-56330a900381:
    -
      -
        attribute: "duration"
        operator: "in?" # options are ==, >=, >, <, <=, in?
        value:
          - "Quelques mois"
          - "1 an"
          - "+ d'1 an"
      -
        attribute: "resources" # discriminant @see app/models/service_offering.rb
        operator: "<=" # options are ==, >=, >, <, <=, in?
        value: 800
      -
        attribute: "current_status" # discriminant @see app/models/service_offering.rb
        operator: "==" # options are ==, >=, >, <, <=, in?
        value: "Étudiant·e"

ensemble2generations:
  trouver-une-chambre-chez-l-habitant:
    -
      -
        attribute: "duration"
        operator: "in?" # options are ==, >=, >, <, <=, in?
        value:
          - "Quelques mois"
          - "1 an"
          - "+ d'1 an"
      -
        attribute: "resources" # discriminant @see app/models/service_offering.rb
        operator: ">=" # options are ==, >=, >, <, <=, in?
        value: 300
      -
        attribute: "current_status" # discriminant @see app/models/service_offering.rb
        operator: "in?" # options are ==, >=, >, <, <=, in?
        value:
          - "Étudiant·e"
          - "Sans activité"
          - "Lycéen·ne"
          - "Salarié·e"
          - "En formation"
          - "Apprenti·e"

residence-quai-207:
  trouver-une-chambre-dans-une-residence-etudiante-privee:
    -
      -
        attribute: "duration"
        operator: "in?" # options are ==, >=, >, <, <=, in?
        value:
          - "Quelques mois"
          - "1 an"
          - "+ d'1 an"
      -
        attribute: "resources" # discriminant @see app/models/service_offering.rb
        operator: "<=" # options are ==, >=, >, <, <=, in?
        value: 700
      -
        attribute: "current_status" # discriminant @see app/models/service_offering.rb
        operator: "==" # options are ==, >=, >, <, <=, in?
        value: "Étudiant·e"

residence-laudine:
  trouver-une-chambre-dans-une-residence-etudiante-privee-fd1fbddf-9a68-4f71-8cf5-56f3f099dbe1:
    -
      -
        attribute: "duration"
        operator: "in?" # options are ==, >=, >, <, <=, in?
        value:
          - "Quelques mois"
          - "1 an"
          - "+ d'1 an"
      -
        attribute: "resources" # discriminant @see app/models/service_offering.rb
        operator: "<=" # options are ==, >=, >, <, <=, in?
        value: 700
      -
        attribute: "current_status" # discriminant @see app/models/service_offering.rb
        operator: "==" # options are ==, >=, >, <, <=, in?
        value: "Étudiant·e"

services-integres-de-l-accueil-et-de-l-orientation:
  trouver-une-solution-de-logement-d-urgence:
    -
      -
        attribute: "duration"
        operator: "==" # options are ==, >=, >, <, <=, in?
        value: "Cette nuit"

centre-international-de-sejour-cis:
  trouver-un-logement-de-courte-duree:
    -
      -
        attribute: "duration"
        operator: "in?" # options are ==, >=, >, <, <=, in?
        value:
          - "Cette nuit"
          - "Quelques mois"
      -
        attribute: "resources" # discriminant @see app/models/service_offering.rb
        operator: "<=" # options are ==, >=, >, <, <=, in?
        value: 400

escale-habitat-jeunes:
  trouves-un-logement-hebergement-temporaire:
    -
      -
        attribute: "duration"
        operator: "in?"
        value:
          - "Quelques mois"
          - "1 an"
      -
        attribute: "current_status"
        operator: "in?"
        value:
          - "Sans activité"
          - "Étudiant·e"
          - "Lycéen·ne"
          - "Collégien.ne"
          - "Salarié·e"
          - "En formation"
          - "Apprenti·e"
          - "Autre"
      -
        attribute: "housing_city"
        operator: "in?"
        value:
          - "Anthenay"
          - "Aougny"
          - "Arcis-le-Ponsart"
          - "Aubérive"
          - "Aubilly"
          - "Auménancourt"
          - "Baslieux-lès-Fismes"
          - "Bazancourt"
          - "Beaumont-sur-Vesle"
          - "Beine-Nauroy"
          - "Berméricourt"
          - "Berru"
          - "Bétheniville"
          - "Bétheny"
          - "Bezannes"
          - "Billy-le-Grand"
          - "Bligny"
          - "Bouilly"
          - "Bouleuse"
          - "Boult-sur-Suippe"
          - "Bourgogne-Fresne"
          - "Bouvancourt"
          - "Branscourt"
          - "Breuil"
          - "Brimont"
          - "Brouillet"
          - "Caurel"
          - "Cauroy-lès-Hermonville"
          - "Cernay-lès-Reims"
          - "Châlons-sur-Vesle"
          - "Chambrecy"
          - "Chamery"
          - "Champfleury"
          - "Champigny"
          - "Chaumuzy"
          - "Chenay"
          - "Chigny-les-Roses"
          - "Cormicy"
          - "Coulommes-la-Montagne"
          - "Courcelles-Sapicourt"
          - "Cormontreuil"
          - "Courcy"
          - "Courlandon"
          - "Courmas"
          - "Courtagnon"
          - "Courville"
          - "Crugny"
          - "Cuisles"
          - "Dontrien"
          - "Écueil"
          - "Époye"
          - "Faverolles-et-Coëmy"
          - "Fismes"
          - "Germigny"
          - "Gueux"
          - "Hermonville"
          - "Heutrégiville"
          - "Hourges"
          - "Isles-sur-Suippe"
          - "Janvry"
          - "Jonchery-sur-Vesle"
          - "Jonquery"
          - "Jouy-lès-Reims"
          - "Lagery"
          - "Lavannes"
          - "Les Mesneux"
          - "Les Petites-Loges"
          - "Lhéry"
          - "Loivre"
          - "Ludes"
          - "Magneux"
          - "Mailly-Champagne"
          - "Marfaux"
          - "Merfy"
          - "Méry-Prémecy"
          - "Montbré"
          - "Montigny-sur-Vesle"
          - "Mont-sur-Courville"
          - "Muizon"
          - "Nogent-l'Abbesse"
          - "Olizy"
          - "Ormes"
          - "Pargny-lès-Reims"
          - "Pévy"
          - "Poilly"
          - "Pomacle"
          - "Pontfaverger-Moronvilliers"
          - "Pouillon"
          - "Pourcy"
          - "Prosnes"
          - "Prouilly"
          - "Prunay"
          - "Puisieulx"
          - "Reims"
          - "Rilly-la-Montagne"
          - "Romain"
          - "Romigny"
          - "Rosnay"
          - "Sacy"
          - "Saint-Brice-Courcelles"
          - "Saint-Étienne-sur-Suippe"
          - "Saint-Euphraise-et-Clairizet"
          - "Saint-Gilles"
          - "Saint-Hilaire-le-Petit"
          - "Saint-Léonard"
          - "Saint-Martin-l'Heureux"
          - "Saint-Masmes"
          - "Saint-Souplet-sur-Py"
          - "Saint-Thierry"
          - "Sarcy"
          - "Savigny-sur-Ardres"
          - "Selles"
          - "Sept-Saulx"
          - "Sermiers"
          - "Serzy-et-Prin"
          - "Sillery"
          - "Taissy"
          - "Thil"
          - "Thillois"
          - "Tinqueux"
          - "Tramery"
          - "Trépail"
          - "Treslon"
          - "Trigny"
          - "Trois-Puits"
          - "Unchair"
          - "Val-de-Vesle"
          - "Vandeuil"
          - "Vaudemange"
          - "Vaudesincourt"
          - "Ventelay"
          - "Verzenay"
          - "Verzy"
          - "Ville-Dommange"
          - "Ville-en-Selve"
          - "Ville-en-Tardenois"
          - "Villers-Allerand"
          - "Villers-aux-Nœuds"
          - "Villers-Franqueux"
          - "Villers-Marmery"
          - "Vrigny"
          - "Warmeriville"
          - "Witry-lès-Reims"

  trouver-une-solution-de-logement-sur-ton-territoire:
    -
      -
        attribute: "duration"
        operator: "in?"
        value:
          - "Quelques mois"
          - "1 an"
          - "+ d'1 an"
      -
        attribute: "current_status"
        operator: "in?"
        value:
          - "Sans activité"
          - "Étudiant·e"
          - "Lycéen·ne"
          - "Collégien.ne"
          - "Salarié·e"
          - "En formation"
          - "Apprenti·e"
          - "Autre"
      -
        attribute: "housing_city"
        operator: "in?"
        value:
          - "Anthenay"
          - "Aougny"
          - "Arcis-le-Ponsart"
          - "Aubérive"
          - "Aubilly"
          - "Auménancourt"
          - "Baslieux-lès-Fismes"
          - "Bazancourt"
          - "Beaumont-sur-Vesle"
          - "Beine-Nauroy"
          - "Berméricourt"
          - "Berru"
          - "Bétheniville"
          - "Bétheny"
          - "Bezannes"
          - "Billy-le-Grand"
          - "Bligny"
          - "Bouilly"
          - "Bouleuse"
          - "Boult-sur-Suippe"
          - "Bourgogne-Fresne"
          - "Bouvancourt"
          - "Branscourt"
          - "Breuil"
          - "Brimont"
          - "Brouillet"
          - "Caurel"
          - "Cauroy-lès-Hermonville"
          - "Cernay-lès-Reims"
          - "Châlons-sur-Vesle"
          - "Chambrecy"
          - "Chamery"
          - "Champfleury"
          - "Champigny"
          - "Chaumuzy"
          - "Chenay"
          - "Chigny-les-Roses"
          - "Cormicy"
          - "Coulommes-la-Montagne"
          - "Courcelles-Sapicourt"
          - "Cormontreuil"
          - "Courcy"
          - "Courlandon"
          - "Courmas"
          - "Courtagnon"
          - "Courville"
          - "Crugny"
          - "Cuisles"
          - "Dontrien"
          - "Écueil"
          - "Époye"
          - "Faverolles-et-Coëmy"
          - "Fismes"
          - "Germigny"
          - "Gueux"
          - "Hermonville"
          - "Heutrégiville"
          - "Hourges"
          - "Isles-sur-Suippe"
          - "Janvry"
          - "Jonchery-sur-Vesle"
          - "Jonquery"
          - "Jouy-lès-Reims"
          - "Lagery"
          - "Lavannes"
          - "Les Mesneux"
          - "Les Petites-Loges"
          - "Lhéry"
          - "Loivre"
          - "Ludes"
          - "Magneux"
          - "Mailly-Champagne"
          - "Marfaux"
          - "Merfy"
          - "Méry-Prémecy"
          - "Montbré"
          - "Montigny-sur-Vesle"
          - "Mont-sur-Courville"
          - "Muizon"
          - "Nogent-l'Abbesse"
          - "Olizy"
          - "Ormes"
          - "Pargny-lès-Reims"
          - "Pévy"
          - "Poilly"
          - "Pomacle"
          - "Pontfaverger-Moronvilliers"
          - "Pouillon"
          - "Pourcy"
          - "Prosnes"
          - "Prouilly"
          - "Prunay"
          - "Puisieulx"
          - "Reims"
          - "Rilly-la-Montagne"
          - "Romain"
          - "Romigny"
          - "Rosnay"
          - "Sacy"
          - "Saint-Brice-Courcelles"
          - "Saint-Étienne-sur-Suippe"
          - "Saint-Euphraise-et-Clairizet"
          - "Saint-Gilles"
          - "Saint-Hilaire-le-Petit"
          - "Saint-Léonard"
          - "Saint-Martin-l'Heureux"
          - "Saint-Masmes"
          - "Saint-Souplet-sur-Py"
          - "Saint-Thierry"
          - "Sarcy"
          - "Savigny-sur-Ardres"
          - "Selles"
          - "Sept-Saulx"
          - "Sermiers"
          - "Serzy-et-Prin"
          - "Sillery"
          - "Taissy"
          - "Thil"
          - "Thillois"
          - "Tinqueux"
          - "Tramery"
          - "Trépail"
          - "Treslon"
          - "Trigny"
          - "Trois-Puits"
          - "Unchair"
          - "Val-de-Vesle"
          - "Vandeuil"
          - "Vaudemange"
          - "Vaudesincourt"
          - "Ventelay"
          - "Verzenay"
          - "Verzy"
          - "Ville-Dommange"
          - "Ville-en-Selve"
          - "Ville-en-Tardenois"
          - "Villers-Allerand"
          - "Villers-aux-Nœuds"
          - "Villers-Franqueux"
          - "Villers-Marmery"
          - "Vrigny"
          - "Warmeriville"
          - "Witry-lès-Reims"
