social_rights:
  - Emploi
  - Logement
  - Formation
  - Santé

public_services:
  siao:
    title: SIAO (Services Intégrés de l’Accueil et de l’Orientation)  # titre, nom de l'acteur
    description: "Le Service intégré de l’accueil et de l’orientation (SIAO) centralise sur chaque territoire la demande et l’offre d’hébergement  pour apporter à chaque demande (urgente ou moins urgente) la réponse la plus adaptée d’hébergement, de logement accompagné ou de logement ordinaire. En cas d’urgence (pour une nuit), un seul numéro à composer : le 115"
    postal_address:  47 rue Docteur Schweitzer, 51100 Reims # adresse postale
    email: siao51@orange.fr
    phone: 03 26 02 30 97
    url:
    response_time_upper_bound: 7
    offer:
      - Trouver un logement pour une nuit
      - Etre accompagné.e pour trouver une solution d'hébergement plus stable

  crous:
    title: CROUS (Centre régional des œuvres universitaires et scolaires) de la Marne (51) # titre, nom de l'acteur
    description: Le Crous, opérateur du service public de la vie étudiante, a pour missions principales, le logement étudiant, la restauration universitaire des étudiants et l’action sociale à travers les bourses et le Fond d’Aide d’Urgence (FNAU). # description général de l'acteur
    postal_address: 31 rue du général Sarrail, 51100 Reims
    email: reims-campus@crous-reims.fr
    phone:  03 26 50 04 59 # téléphone
    url: http://www.crous-reims.fr/
    response_time_upper_bound: 7
    offer:
      - T'informer sur le logement en résidence universitaire
      - Faire le suivi de ton Dossier Social Étudiant

  lokaviz:
    title: Lokaviz
    description: La centrale du logement étudiant
    email: lokaviz@orange.fr
    url: http://www.lokaviz.fr/
    response_time_upper_bound: 7
    offer:
      - Trouver un logement étudiant chez un particulier

  paindavoine:
    title: FJT (Foyer de Jeunes Travailleurs) Léon Paindavoine
    description: Les foyers de jeunes travailleurs (FJT) ont pour mission d'accueillir des jeunes en formation ou exerçant une activité professionnelle. Ils proposent un hébergement temporaire comportant à la fois des locaux privatifs (meublés ou non) et des locaux communs affectés à la vie collective. Ils  s'adressent essentiellement aux jeunes travailleurs vivant seuls, âgés de 16 à 25 ans et exerçant une activité professionnelle ou suivant une formation professionnelle (par ex. stage ou apprentissage). Certains établissements accueillent également des étudiants ou des demandeurs d'emploiLa durée de l'hébergement est généralement de 2 ans maximum. # description général de l'acteur
    postal_address: 1 rue du Lieut Herduin, 51100 Reims
    email: residence.paindavoine@noelpaindavoine.fr
    phone:  03 26 61 48 00
    url:
    response_time_upper_bound: 7
    offer:
      - Trouver différents types de logements en foyer
      - T'aider à trouver une solution logement sur ton territoire

  action_logement:
    title: Action Logement
    description: Action Logement (ex 1% Logement) gère la Participation des Employeurs à l’Effort de Construction (PEEC).
    postal_address: Agence Aliance Territoires 38 rue Cérès, 51100 Reims
    email: agence.reims@alianceterritoires.fr
    phone: 03 26 04 29 38
    url: http://www.alianceterritoires.fr/
    response_time_upper_bound: 7
    offer:
      - Te proposer une offre de logements à louer
      - Te proposer une offre de logement pour tous les budgets

  caf:
    title: CAF (Caisse d'Allocations Familiales)
    description: La CAF les aides au logement (APL).
    postal_address: 202 Rue des Capucins, 51087 Reims
    email: caf@orange.fr
    phone: 0 810 25 51 10
    url: https://www.caf.fr/ma-caf/caf-de-la-marne/points-d-accueil/reims
    response_time_upper_bound: 7
    offer:
      - Simuler le montant de son APL
      - T'aider à remplir la demande d'APL


  crij:
    title: CRIJ (Centre Régional d'Information Jeunesse)
    description: Le CRIJ de Reims accueille, informe et conseille les jeunes et tous les publics dans tous les domaines qui les intéressent.
    postal_address: 41 rue de Talleyrand 51100 Reims
    email: ijca@crij-ca.fr
    phone: 03 26 79 84 79
    url: jeunes-ca.fr
    response_time_upper_bound: 7
    offer:
      - Découvrir les solutions logement sur ton territoire


  mgel:
    title: MGEL (Mutuelle générale des étudiants de l'Est)
    description: La MGEL gère le régime étudiant de la Sécurité sociale. Elle propose aussi des places en résidences dans la région Grand Est.
    postal_address: 1-3, boulevard du docteur Henri Henrot 51100 ReimS
    email: mgel@orange.fr
    url: http://www.mgellogement.fr/
    response_time_upper_bound: 7
    offer:
      - Trouver une chambre dans une résidence étudiante privée

measures:
  cent_quinze:
    title: 115
    description: Le 115 est un numéro d'urgence à n'utiliser que si vous êtes sans possibilité d'hébergement au moment de l'appel. N'appelez pas le 115 tant que vous disposez encore d'un logement ou êtes logé chez un tiers. Le 115 octroie des places au jour le jour.
    url: http://www.gouvernement.fr/sites/default/files/contenu/piece-jointe/2014/10/dihal_-_annuaire_siao_ecran.pdf
    public_service: siao

  apl:
    title: L’APL (Aide personnalisée au logement)
    description: L’APL est une aide au paiement des loyers qui est délivrée par la CAF (peut être remplacée par l'Allocation logement à caractère social (ALS) si le logement n'est pas conventionné par l'Etat.
    url: http://www.caf.fr/aides-et-services/les-services-en-ligne/estimer-vos-droits
    public_service: caf

  cle:
    title: La CLÉ (caution locative étudiante)
    description: La Clé est une garantie de l'Etat qui permet aux étudiants dépourvus de garants personnels de faciliter leur accès à un logement. La Clé est gérée par les Crous.
    url: http://www.lokaviz.fr/n/a-qui-s-adresse-la-cle/n:473
    public_service: crous

  locapass:
    title: Garantie Loca-Pass
    description: Caution accordée au locataire pour prendre en charge le paiement du loyer et des charges de sa résidence principale en cas de défaillance pour les jeunes de moins de 30 ans.
    url: http://www.actionlogement.fr/media/upload/Fiches_Produits_2015/PP/20150409GarantieLOCA-PASS.pdf
    public_service: action_logement

  visale:
    title: Garantie VISALE locataire et bailleur
    description: La garantie Visale est un engagement gratuit pour le locataire et le bailleur. Le dispositif vise à couvrir les impayés de loyers (charges comprises) du locataire, quelle qu'en soit la cause au cours des trois premières années du bail et dans la limite du départ du locataire
    url: https://www.visale.fr/#/
    public_service: action_logement
